# Generated by Django 5.1.4 on 2024-12-29 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Utilisateur', 'verbose_name_plural': 'Utilisateurs'},
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='Les groupes auxquels appartient cet utilisateur.', related_name='custom_user_groups', to='auth.group', verbose_name='groupes'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('client', 'Client'), ('mechanic', 'Mechanic')], default='client', max_length=10, verbose_name="Rôle de l'utilisateur"),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Permissions spécifiques pour cet utilisateur.', related_name='custom_user_permissions', to='auth.permission', verbose_name="permissions d'utilisateur"),
        ),
    ]
